using System.Diagnostics;
using System.IO.Ports;
using System.Net;
using System.Net.NetworkInformation;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Configuration;

namespace AccessControll.Hardware;

/// <summary>
/// Handles ESP8266 provisioning via build-time config injection:
///   1. WriteConfigHeader — writes config.h with WiFi creds + server pubkey
///   2. FlashFirmwareAsync — compiles sketch (with config.h baked in) and uploads
///   3. On first boot the sketch reads config.h and writes credentials to EEPROM
///
/// UART roundtrip (ProvisionAsync) is kept for adapters that support DTR/RTS.
/// </summary>
public class ProvisioningService
{
    private readonly IConfiguration _config;
    private readonly ServerKeyService _keyService;

    public ProvisioningService(IConfiguration config, ServerKeyService keyService)
    {
        _config     = config;
        _keyService = keyService;
    }

    // ── Network helpers ───────────────────────────────────────────────────────

    /// <summary>
    /// Returns the server's own LAN IPv4 address.
    /// Only considers real Ethernet/Wi-Fi adapters — skips VPN tunnels, PPP, and virtual interfaces.
    /// </summary>
    public static string GetServerLocalIp()
    {
        var physicalTypes = new[]
        {
            NetworkInterfaceType.Ethernet,
            NetworkInterfaceType.Wireless80211,
            NetworkInterfaceType.GigabitEthernet,
            NetworkInterfaceType.FastEthernetFx,
            NetworkInterfaceType.FastEthernetT,
        };

        foreach (var ni in NetworkInterface.GetAllNetworkInterfaces())
        {
            if (ni.OperationalStatus != OperationalStatus.Up) continue;
            if (!physicalTypes.Contains(ni.NetworkInterfaceType)) continue;

            foreach (var ua in ni.GetIPProperties().UnicastAddresses)
            {
                if (ua.Address.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork
                    && !IPAddress.IsLoopback(ua.Address))
                    return ua.Address.ToString();
            }
        }
        return "127.0.0.1";
    }

    // ── Serial ports ─────────────────────────────────────────────────────────

    /// <summary>Returns all serial ports visible on the host OS.</summary>
    public static string[] GetAvailablePorts() => SerialPort.GetPortNames();

    // ── arduino-cli check ────────────────────────────────────────────────────

    /// <summary>
    /// Returns the path to arduino-cli if it is available on PATH, otherwise null.
    /// </summary>
    public static string? FindArduinoCli()
    {
        var exe = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
            ? "arduino-cli.exe" : "arduino-cli";

        var pathEnv = Environment.GetEnvironmentVariable("PATH") ?? "";
        foreach (var dir in pathEnv.Split(Path.PathSeparator))
        {
            var full = Path.Combine(dir.Trim(), exe);
            if (File.Exists(full)) return full;
        }
        return null;
    }

    // ── Build-time config injection ──────────────────────────────────────────

    /// <summary>
    /// Writes <c>config.h</c> into the sketch directory with WiFi credentials,
    /// server address, and P-256 public key baked in as #define macros.
    /// Must be called before <see cref="FlashFirmwareAsync"/> so the compiler
    /// picks up the updated values.
    /// </summary>
    /// <param name="stationType">0=General, 1=Door, 2=RemoteControl — baked into firmware.</param>
    public void WriteConfigHeader(string ssid, string password, int stationType = 0, string? serverHostOverride = null, int? serverPortOverride = null)
    {
        var sketchPath = GetSketchPath()
            ?? throw new InvalidOperationException("Sketch path not found");

        var host = serverHostOverride
            ?? (string.IsNullOrEmpty(_config["SignalR:Host"]) ? GetServerLocalIp() : _config["SignalR:Host"]!);

        var port = serverPortOverride
            ?? (int.TryParse(_config["SignalR:Port"], out var p) ? p : 5000);

        var content =
            $"""
            #pragma once

            // Auto-generated by ProvisioningService — do not edit manually.
            // Regenerated before each flash with WriteConfigHeader().

            #define CFG_WIFI_SSID     "{ssid}"
            #define CFG_WIFI_PASSWORD "{password}"
            #define CFG_SERVER_HOST   "{host}"
            #define CFG_SERVER_PORT   {port}
            #define CFG_SERVER_PUBKEY "{_keyService.PublicKeyHex}"
            #define CFG_STATION_TYPE  {stationType}

            """;

        File.WriteAllText(Path.Combine(sketchPath, "config.h"), content);
    }

    // ── Firmware flash ───────────────────────────────────────────────────────

    /// <summary>
    /// Compiles and uploads the station sketch using arduino-cli.
    /// <paramref name="onLine"/> is invoked for each output line as it arrives (live streaming).
    /// Returns (Success, full combined output).
    /// </summary>
    public async Task<(bool Success, string Output)> FlashFirmwareAsync(
        string portName, Action<string>? onLine = null)
    {
        var cli = FindArduinoCli();
        if (cli is null)
        {
            var msg =
                "arduino-cli یافت نشد.\n" +
                "لطفاً آن را نصب کنید: https://arduino.github.io/arduino-cli/\n" +
                "سپس ESP8266 core را اضافه کنید:\n" +
                "  arduino-cli core install esp8266:esp8266";
            onLine?.Invoke(msg);
            return (false, msg);
        }

        var sketchPath = GetSketchPath();
        if (sketchPath is null)
        {
            var msg = "پوشه sketch یافت نشد. مسیر را در appsettings.json تنظیم کنید (ArduinoCli:SketchPath).";
            onLine?.Invoke(msg);
            return (false, msg);
        }

        var fqbn = _config["ArduinoCli:Fqbn"] ?? "esp8266:esp8266:generic";
        var args = $"compile --fqbn {fqbn} --upload --port {portName} \"{sketchPath}\"";

        var psi = new ProcessStartInfo(cli, args)
        {
            RedirectStandardOutput = true,
            RedirectStandardError  = true,
            UseShellExecute        = false,
        };

        using var proc = Process.Start(psi)
            ?? throw new InvalidOperationException("فرآیند arduino-cli شروع نشد");

        var sb = new System.Text.StringBuilder();

        void HandleLine(string? line)
        {
            if (line is null) return;
            sb.AppendLine(line);
            onLine?.Invoke(line);
        }

        proc.OutputDataReceived += (_, e) => HandleLine(e.Data);
        proc.ErrorDataReceived  += (_, e) => HandleLine(e.Data);
        proc.BeginOutputReadLine();
        proc.BeginErrorReadLine();

        var cts = new CancellationTokenSource(TimeSpan.FromMinutes(3));
        await proc.WaitForExitAsync(cts.Token);

        return proc.ExitCode == 0
            ? (true,  sb.ToString())
            : (false, sb.ToString());
    }

    // ── MAC extraction ───────────────────────────────────────────────────────

    /// <summary>
    /// Parses the esptool/arduino-cli output to find the ESP's MAC address.
    /// esptool prints a line like: "MAC: bc:dd:c2:79:bc:60"
    /// </summary>
    public static string? ExtractMacFromOutput(string output)
    {
        var m = Regex.Match(output, @"MAC:\s*([0-9a-fA-F]{2}(?::[0-9a-fA-F]{2}){5})",
            RegexOptions.IgnoreCase);
        return m.Success ? m.Groups[1].Value.ToUpperInvariant() : null;
    }

    // ── Legacy UART roundtrip (requires DTR/RTS on USB-Serial adapter) ────────

    /// <summary>
    /// Opens <paramref name="portName"/>, sends PROVISION command to the ESP and
    /// waits for <c>OK:{mac}</c> response (15-second timeout).
    /// Only works with adapters that have DTR/RTS pins for auto-reset.
    /// </summary>
    public async Task<ProvisionResult> ProvisionAsync(string portName, string ssid, string password)
    {
        var host = string.IsNullOrEmpty(_config["SignalR:Host"])
            ? GetServerLocalIp()
            : _config["SignalR:Host"]!;

        var port = int.TryParse(_config["SignalR:Port"], out var p) ? p : 5000;

        var payload = JsonSerializer.Serialize(new { ssid, password, server = host, port, pubkey = _keyService.PublicKeyHex });
        var command = $"PROVISION:{payload}\n";   // \n = 0x0A newline (not verbatim string)

        using var serial = new SerialPort(portName, 115200)
        {
            ReadTimeout  = 15_000,
            WriteTimeout = 3_000,
            NewLine      = "\n",
            DtrEnable    = false,
            RtsEnable    = false,
        };

        try { serial.Open(); }
        catch (Exception ex)
        {
            return new ProvisionResult(false, null, $"خطا در باز کردن پورت: {ex.Message}");
        }

        // Send immediately for a running ESP; also resend after boot if it reset.
        await Task.Delay(500);
        serial.Write(command);

        bool resent  = false;
        var deadline = DateTime.UtcNow.AddSeconds(25);

        while (DateTime.UtcNow < deadline)
        {
            if (serial.BytesToRead > 0)
            {
                try
                {
                    var line = serial.ReadLine().Trim();

                    // Only match OK:{ to avoid false positives like "OK: Keypad at 0x20"
                    if (line.StartsWith("OK:{"))
                    {
                        try
                        {
                            var json = JsonSerializer.Deserialize<JsonElement>(line[3..]);
                            var mac  = json.TryGetProperty("mac", out var m2) ? m2.GetString() : null;
                            if (mac != null) return new ProvisionResult(true, mac, null);
                        }
                        catch { /* malformed line — keep waiting */ }
                    }

                    if (line.StartsWith("ERR:"))
                        return new ProvisionResult(false, null, line[4..]);

                    // ESP rebooted due to DTR pulse — resend PROVISION after it says Ready
                    if (!resent && line.Contains("--- Ready ---"))
                    {
                        resent = true;
                        await Task.Delay(300);
                        serial.Write(command);
                    }
                }
                catch (TimeoutException) { /* keep waiting */ }
            }

            await Task.Delay(100);
        }

        return new ProvisionResult(false, null, "تایم‌اوت: ESP پاسخ نداد");
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    public string? GetSketchPath()
    {
        // 1. Explicit config
        var configPath = _config["ArduinoCli:SketchPath"];
        if (!string.IsNullOrEmpty(configPath) && Directory.Exists(configPath))
            return configPath;

        // 2. Walk up from the running assembly to find the repo root
        var dir = AppContext.BaseDirectory;
        for (int i = 0; i < 8; i++)
        {
            var candidate = Path.Combine(dir, "src", "AccessControll.Station", "sketch_feb19b");
            if (Directory.Exists(candidate)) return candidate;
            var parent = Directory.GetParent(dir);
            if (parent is null) break;
            dir = parent.FullName;
        }

        return null;
    }
}

public record ProvisionResult(bool Success, string? Mac, string? Error);
