#pragma once

// Auto-generated by ProvisioningService — do not edit manually.
// Regenerated before each flash with WriteConfigHeader().

#define CFG_WIFI_SSID     "$(M_2.4_M)$"
#define CFG_WIFI_PASSWORD "M@ein#1383"
#define CFG_SERVER_HOST   "192.168.254.54"
#define CFG_SERVER_PORT   5000
#define CFG_SERVER_PUBKEY "8a33433e35f3f279bea800a4cb1e3e8616435f5e9e063121ec62a24be7806808f3cace1c71ab6542a2dbea6657b4382405577e0bceaf3767c66d5f961ea6cca8"
#define CFG_STATION_TYPE  2
